### ISSUE TITLE
Building with nix

### ISSUE THREAD

**Issue by bbarker** [vmchale/atspkg#5]
This is my first stab at adding a haskell package to nix; unfortunately the build seems to fail near the end? See nixpkgs PR at https://github.com/NixOS/nixpkgs/pull/44887  - any suggestions would be welcome.

**Comment by vmchale** [comment]
I believe the problem is that `language-ats` versions prior to `1.7.0.1` failed to include the correct test data. Hopefully, once the bound is bumped the rest of the packages will also work? But I'll leave this open in case they don't.

**Comment by bbarker** [comment]
Ah ok - I see the requirement `language-ats >=1.5.0.0` - so does Cabal just grab the closest version that matches the requirement rather than the most recent (since I believe I saw 1.7.0.1 up on Hackage), or is it some other decision based on semantic versioning?
