### ISSUE TITLE
Which repository is master? GitHub or Darcs?

### ISSUE THREAD

**Issue by master-q** [vmchale/atspkg#8]
Which repository is master? GitHub or Darcs?

* https://github.com/vmchale/atspkg
* https://hub.darcs.net/vmchale/ats

I would like to use your language-ats library, which is located at both of above.

**Comment by vmchale** [comment]
I think the GitHub should be treated as "master" for now, as I get email notifications :)

Depending on what you need `language-ats` for, it may be possible to simply download from Hackage. It's buggy, but stable.

**Comment by master-q** [comment]
Thanks. I will send PR on GitHub, if I would have new feature.
